# Nimbus Insights Deployment Script
# This script handles the complete deployment process

param(
    [switch]$Clean,
    [switch]$SkipBuild,
    [string]$StackName = "nimbus-insights"
)

Write-Host "🚀 Nimbus Insights Deployment Script" -ForegroundColor Cyan
Write-Host "=====================================" -ForegroundColor Cyan
Write-Host ""

# Check if AWS CLI is configured
try {
    $awsIdentity = aws sts get-caller-identity 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host "❌ AWS CLI not configured. Run 'aws configure' first." -ForegroundColor Red
        exit 1
    }
    Write-Host "✅ AWS credentials validated" -ForegroundColor Green
} catch {
    Write-Host "❌ AWS CLI not found. Please install AWS CLI v2." -ForegroundColor Red
    exit 1
}

# Clean existing stack if requested
if ($Clean) {
    Write-Host ""
    Write-Host "🧹 Cleaning existing stack..." -ForegroundColor Yellow
    aws cloudformation delete-stack --stack-name $StackName
    Write-Host "⏳ Waiting for stack deletion to complete..." -ForegroundColor Yellow
    aws cloudformation wait stack-delete-complete --stack-name $StackName 2>$null
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✅ Stack deleted successfully" -ForegroundColor Green
    } else {
        Write-Host "⚠️  No existing stack found or deletion failed (continuing anyway)" -ForegroundColor Yellow
    }
}

# Build the SAM application
if (-not $SkipBuild) {
    Write-Host ""
    Write-Host "🔨 Building SAM application..." -ForegroundColor Cyan
    sam build --template-file infrastructure/template.yaml
    if ($LASTEXITCODE -ne 0) {
        Write-Host "❌ Build failed" -ForegroundColor Red
        exit 1
    }
    Write-Host "✅ Build completed successfully" -ForegroundColor Green
} else {
    Write-Host ""
    Write-Host "⏭️  Skipping build step" -ForegroundColor Yellow
}

# Deploy the application
Write-Host ""
Write-Host "📦 Deploying to AWS..." -ForegroundColor Cyan
sam deploy --template-file infrastructure/template.yaml --no-confirm-changeset
if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Deployment failed" -ForegroundColor Red
    exit 1
}

# Get the API URL from stack outputs
Write-Host ""
Write-Host "🔍 Retrieving API endpoint..." -ForegroundColor Cyan
$outputs = aws cloudformation describe-stacks --stack-name $StackName --query "Stacks[0].Outputs" --output json | ConvertFrom-Json

$apiUrl = ($outputs | Where-Object { $_.OutputKey -eq "ApiUrl" }).OutputValue
$uploadBucket = ($outputs | Where-Object { $_.OutputKey -eq "UploadBucketName" }).OutputValue
$reportBucket = ($outputs | Where-Object { $_.OutputKey -eq "ReportBucketName" }).OutputValue

Write-Host ""
Write-Host "✅ Deployment completed successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "📋 Stack Outputs:" -ForegroundColor Cyan
Write-Host "  API URL: $apiUrl" -ForegroundColor White
Write-Host "  Upload Bucket: $uploadBucket" -ForegroundColor White
Write-Host "  Report Bucket: $reportBucket" -ForegroundColor White
Write-Host ""
Write-Host "📝 Next Steps:" -ForegroundColor Yellow
Write-Host "  1. Update frontend/config.js with the API URL above" -ForegroundColor White
Write-Host "  2. Test with: samples/valid.csv" -ForegroundColor White
Write-Host "  3. (Optional) Deploy frontend to S3 for static hosting" -ForegroundColor White
Write-Host ""

# Offer to update frontend config automatically
$response = Read-Host "Would you like to update frontend/config.js automatically? (y/n)"
if ($response -eq "y" -or $response -eq "Y") {
    $configContent = "window.APP_CONFIG = {`n  // Auto-generated by deploy.ps1`n  apiBaseUrl: `"$apiUrl`",`n};"
    Set-Content -Path "frontend\config.js" -Value $configContent -Encoding UTF8
    Write-Host "Success! Frontend config updated!" -ForegroundColor Green
    Write-Host ""
    Write-Host "You can now test the frontend locally by opening frontend\index.html" -ForegroundColor Cyan
}

Write-Host ""
Write-Host "All done!" -ForegroundColor Green
